context:
    data:
        -   link: true
            name: リンクテキスト
            func: /example/
        -   link: false
            name: submitボタン
            func: submit
        -   link: false
            name: buttonボタン
            func: button