context:
    datas:
        -   items:
                link: true
                name: リンクテキスト
                func: /example/
        -   items:
                link: false
                name: submitボタン
                func: submit
        -   items:
                link: false
                name: buttonテキスト
                func: button