context:
    datas:
        -   items:
                -   name: pen
        -   items:
                -   name: laptop
        -   items:
                -   name: htmltag
        -   items:
                -   name: tag