context:
    datas:
        -   items:
                -   name: Webデザイン
                -   name: フロントエンド構築
                -   name: バックエンド構築
                -   name: ロゴデザイン
                -   name: 名刺デザイン
        -   modifier: status
            items:
                -   name: Webデザイン
                    active: true
                -   name: フロントエンド構築
                    active: true
                -   name: バックエンド構築
                    active: false
                -   name: ロゴデザイン
                    active: false
                -   name: 名刺デザイン
                    active: false
        -   modifier: toggle
            items:
                -   name: Webデザイン
                    active: true
                -   name: フロントエンド構築
                    active: true
                -   name: バックエンド構築
                    active: false
                -   name: ロゴデザイン
                    active: false
                -   name: 名刺デザイン
                    active: false