version: '3'
services:
    web:
        image: nginx:1.17.8-alpine
        env_file: ./.env
        volumes:
            - ./dist:/var/www/html
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - shared
        restart: always

networks:
    shared:
        external: true