version: '3'
services:
    https-portal:
        image: steveltn/https-portal:1
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            DOMAINS: 'monoweb.jp.local -> http://web:8000'
            STAGE: local
        volumes:
            - ./org-chimata-ssl-certs:/var/lib/https-portal
    web:
        image: nginx:1.17.8-alpine
        ports:
            - '8000:8000'
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./dist:/var/www/html
